// =====================================
// SmartBook PDF Module
// =====================================

console.log("PDF Module Loaded");

document.addEventListener("DOMContentLoaded", function () {

    const pdfButton = document.getElementById("exportPDF");

    if (!pdfButton) {
        console.error("找不到 exportPDF 按鈕");
        return;
    }

    console.log("PDF 按鈕綁定成功");

    pdfButton.addEventListener("click", function () {

        console.log("已點擊 PDF 按鈕");

        if (
            !window.jspdf ||
            !window.jspdf.jsPDF
        ) {
            alert("jsPDF 尚未成功載入！");
            console.error("找不到 window.jspdf.jsPDF");
            return;
        }

        const { jsPDF } = window.jspdf;

        const income =
            document.getElementById("reportIncome")
                ?.textContent.trim() || "NT$ 0";

        const expense =
            document.getElementById("reportExpense")
                ?.textContent.trim() || "NT$ 0";

        const advance =
            document.getElementById("reportAdvance")
                ?.textContent.trim() || "NT$ 0";

        const balance =
            document.getElementById("reportBalance")
                ?.textContent.trim() || "NT$ 0";

        const today = new Date();

        const year = today.getFullYear();
        const month =
            String(today.getMonth() + 1).padStart(2, "0");
        const day =
            String(today.getDate()).padStart(2, "0");

        const pdf = new jsPDF();

        pdf.setFontSize(22);
        pdf.text("SmartBook Monthly Report", 20, 25);

        pdf.setFontSize(12);
        pdf.text(`Month: ${year}/${month}`, 20, 38);
        pdf.text(
            `Export date: ${year}/${month}/${day}`,
            20,
            46
        );

        pdf.line(20, 52, 190, 52);

        pdf.setFontSize(16);
        pdf.text("Monthly Summary", 20, 65);

        pdf.setFontSize(13);
        pdf.text(`Income: ${income}`, 25, 80);
        pdf.text(`Expense: ${expense}`, 25, 92);
        pdf.text(
            `Outstanding advances: ${advance}`,
            25,
            104
        );
        pdf.text(`Balance: ${balance}`, 25, 116);

        pdf.line(20, 126, 190, 126);

        pdf.setFontSize(10);
        pdf.text(
            "Generated by SmartBook V4.2",
            20,
            140
        );

        pdf.save(`SmartBook_${year}-${month}.pdf`);

    });

});